// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SeshDB.Data.Sesh
{
    public partial class Categories
    {
        public Categories()
        {
            Transactions = new HashSet<Transactions>();
        }

        public int ItemId { get; set; }
        public int? ClassId { get; set; }
        public string BudgetItemName { get; set; }
        public int? BudgetedAmount { get; set; }
        public DateTime? LastActiveMonth { get; set; }
        public int? CurrentBalance { get; set; }
        public string UserName { get; set; }

        public virtual Classifications Class { get; set; }
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}