// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SeshDB.Data.Sesh
{
    public partial class Classifications
    {
        public Classifications()
        {
            BudgetedItems = new HashSet<Categories>();
        }

        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public string UserName { get; set; }

        public virtual ICollection<Categories> BudgetedItems { get; set; }
    }
}