// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SeshDB.Data.Sesh
{
    public partial class Payees
    {
        public Payees()
        {
            Transactions = new HashSet<Transactions>();
        }

        public int PayeeId { get; set; }
        public string PayeeName { get; set; }
        public string UserName { get; set; }

        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}