// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace SeshDB.Data.Sesh
{
    public partial class SeshContext : DbContext
    {
        public SeshContext()
        {
        }

        public SeshContext(DbContextOptions<SeshContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Classifications> Classifications { get; set; }
        public virtual DbSet<Payees> Payees { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<Accounts>(entity =>
            {
                entity.HasKey(e => e.AccountId)
                    .HasName("PK__tmp_ms_x__349DA5A64BDCB432");

                entity.Property(e => e.AccountName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.UserName)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<Categories>(entity =>
            {
                entity.HasKey(e => e.ItemId)
                    .HasName("PK__Budgeted__727E838B0D1A96B4");

                entity.Property(e => e.BudgetItemName).HasMaxLength(50);

                entity.Property(e => e.LastActiveMonth).HasColumnType("datetime");

                entity.Property(e => e.UserName).HasMaxLength(50);

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.BudgetedItems)
                    .HasForeignKey(d => d.ClassId)
                    .HasConstraintName("FK__BudgetedI__Class__3A81B327");
            });

            modelBuilder.Entity<Classifications>(entity =>
            {
                entity.HasKey(e => e.ClassId)
                    .HasName("PK__Classifi__CB1927C0605E4D01");

                entity.Property(e => e.ClassName).HasMaxLength(50);

                entity.Property(e => e.UserName).HasMaxLength(50);
            });

            modelBuilder.Entity<Payees>(entity =>
            {
                entity.HasKey(e => e.PayeeId)
                    .HasName("PK__Payees__0BC3E4D9022D12F1");

                entity.Property(e => e.PayeeName).HasMaxLength(50);

                entity.Property(e => e.UserName).HasMaxLength(50);
            });

            modelBuilder.Entity<Transactions>(entity =>
            {
                entity.HasKey(e => e.TransactionId)
                    .HasName("PK__Transact__55433A6BDB3087BA");

                entity.Property(e => e.Memo).HasMaxLength(50);

                entity.Property(e => e.TransactionDate).HasColumnType("datetime");

                entity.HasOne(d => d.Account)
                    .WithMany(p => p.Transactions)
                    .HasForeignKey(d => d.AccountId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Transacti__Accou__46E78A0C");

                entity.HasOne(d => d.Item)
                    .WithMany(p => p.Transactions)
                    .HasForeignKey(d => d.ItemId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Transacti__ItemI__440B1D61");

                entity.HasOne(d => d.Payee)
                    .WithMany(p => p.Transactions)
                    .HasForeignKey(d => d.PayeeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Transacti__Payee__4316F928");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}