// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SeshDB.Data.Sesh
{
    public partial class Transactions
    {
        public int TransactionId { get; set; }
        public int AccountId { get; set; }
        public DateTime TransactionDate { get; set; }
        public int PayeeId { get; set; }
        public int ItemId { get; set; }
        public string Memo { get; set; }
        public int? DebitAmount { get; set; }
        public int? CreditAmount { get; set; }
        public string UserName { get; set; }

        public virtual Accounts Account { get; set; }
        public virtual Categories Item { get; set; }
        public virtual Payees Payee { get; set; }
    }
}